### ISSUE TITLE
Another htmlPy application is already running

### ISSUE THREAD

**Issue by Priler** [amol-mandhane/htmlPy#10]
Example not work.
Here is output:

```
Traceback (most recent call last):
  File "main.py", line 28, in say_hello_world
    from main import app
  File "/home/abraham/My Items/Git my repos/Silk Strider/test/main.py", line 11, in <module>
    app = htmlPy.AppGUI(title=u"Application", maximized=True, plugins=True)
  File "/usr/local/lib/python2.7/dist-packages/htmlPy/app_gui.py", line 103, in __init__
    super(AppGUI, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/htmlPy/base_gui.py", line 76, in __init__
    raise RuntimeError("Another htmlPy application is already running")
RuntimeError: Another htmlPy application is already running
```

Restarting of PC does not help.

**Comment by d0n601** [comment]
Same issue when importing app

**Comment by louiepsp** [comment]
Been trying this for a few days and can't find any help. 
If anyone has solved this I would love to know how. Thanks
I have this outputting in my console.

`/Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 /Users/badmin/PycharmProjects/untitled4/main.py
Traceback (most recent call last):
  File "/Users/badmin/PycharmProjects/untitled4/back_end.py", line 7, in say_hello_world
    from main import app
  File "/Users/badmin/PycharmProjects/untitled4/main.py", line 5, in <module>
    title=u"Sample application")
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/htmlPy/app_gui.py", line 103, in __init__
    super(AppGUI, self).__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/htmlPy/base_gui.py", line 76, in __init__
    raise RuntimeError("Another htmlPy application is already running")
RuntimeError: Another htmlPy application is already running`

**Comment by louiepsp** [comment]
## Here is the solution guys. (FINALLY!)

## main.py

```
import htmlPy
from back_end import BackEnd

app = htmlPy.AppGUI(title=u'Sample application')
app.maximized = True
app.template_path = "."
app.bind(BackEnd(app))
app.template = ("index.html", {})
if __name__ == "__main__":
    app.start()
```

---

## index.html

```
<html>
  <body>
    <a
    href="BackEnd.say_hello_world"
    data-bind="true">
      Click to say "Hello, world"
    </a>
    <br>
  </body>
</html>
```

---

## back_end.py

```
import htmlPy
class BackEnd(htmlPy.Object):

    def __init__(self, app_gui):
        super(BackEnd, self).__init__()
        self.app_gui = app_gui

    @htmlPy.Slot()
    def say_hello_world(self):
        self.app_gui.html = u"Hello, world"`
```

**Comment by amol-mandhane** [comment]
Updated the example.

**Comment by revliscano** [comment]
The solution given by Louipsp worked fine for me.

**Comment by thebitpost** [comment]
Can there be 2 htmmlPy apps run at the same time?. I get the same error, when I try to run 2/3 apps from one thread by calling daemon threads.
